version: 2.1

orbs:
  node: circleci/node@4.3.0
  ruby: circleci/ruby@1.1.3

workflows:
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: 'cimg/base:stable'     
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
      - ruby/install:
          version: '2.7'
      - ruby/install-deps
      - run:
          name: 'Specs'
          command: yarn test
      - run:
          name: 'Lint'
          command: yarn lint
      - run:
          name: 'Coverage'
          command: yarn coveralls