version: 2.1

orbs:
  node: circleci/node@4.3.0
  ruby: circleci/ruby@1.1.4

workflows:
  version: 2
  test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/base:stable

jobs:
  test:
    <<: *defaults   
    environment:
      GEM_HOME: ~/bundle
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - ruby/install:
          version: '2.7.2'
      - restore_cache:
          keys:
            - gems-v1-{{ checksum "./Gemfile.lock"  }}-{{ .Branch }}
      - run:
          name: 'Bundle install'
          command: bundle install
      - save_cache:
          key: gems-v1-{{ checksum "./Gemfile.lock"  }}-{{ .Branch }}
          paths:
            - ~/bundle
      - run:
          name: 'Unit specs'
          command: yarn test
      - run:
          name: 'e2e specs'
          command: yarn e2e
      - run:
          name: 'Lint'
          command: yarn lint
      - run:
          name: 'Coverage'
          command: yarn coveralls
      - persist_to_workspace:
          root: ~/repo
          paths: ./
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - node/install:
          install-npm: true
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

